// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: weathercontrol.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	mi := &file_weathercontrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weathercontrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weathercontrol_proto_rawDescGZIP(), []int{0}
}

type GetWeatherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeatherType string `protobuf:"bytes,1,opt,name=weather_type,json=weatherType,proto3" json:"weather_type,omitempty"`
	Intensity   int32  `protobuf:"varint,2,opt,name=intensity,proto3" json:"intensity,omitempty"`
}

func (x *GetWeatherResponse) Reset() {
	*x = GetWeatherResponse{}
	mi := &file_weathercontrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResponse) ProtoMessage() {}

func (x *GetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weathercontrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weathercontrol_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherResponse) GetWeatherType() string {
	if x != nil {
		return x.WeatherType
	}
	return ""
}

func (x *GetWeatherResponse) GetIntensity() int32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type SetWeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeatherType string `protobuf:"bytes,1,opt,name=weather_type,json=weatherType,proto3" json:"weather_type,omitempty"`
	Intensity   int32  `protobuf:"varint,2,opt,name=intensity,proto3" json:"intensity,omitempty"`
}

func (x *SetWeatherRequest) Reset() {
	*x = SetWeatherRequest{}
	mi := &file_weathercontrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWeatherRequest) ProtoMessage() {}

func (x *SetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weathercontrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWeatherRequest.ProtoReflect.Descriptor instead.
func (*SetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weathercontrol_proto_rawDescGZIP(), []int{2}
}

func (x *SetWeatherRequest) GetWeatherType() string {
	if x != nil {
		return x.WeatherType
	}
	return ""
}

func (x *SetWeatherRequest) GetIntensity() int32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type SetWeatherResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetWeatherResponse) Reset() {
	*x = SetWeatherResponse{}
	mi := &file_weathercontrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWeatherResponse) ProtoMessage() {}

func (x *SetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weathercontrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWeatherResponse.ProtoReflect.Descriptor instead.
func (*SetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weathercontrol_proto_rawDescGZIP(), []int{3}
}

func (x *SetWeatherResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_weathercontrol_proto protoreflect.FileDescriptor

var file_weathercontrol_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x74, 0x79, 0x22, 0x54, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x12, 0x53,
	0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xd1, 0x01, 0x0a, 0x15,
	0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x12, 0x24, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_weathercontrol_proto_rawDescOnce sync.Once
	file_weathercontrol_proto_rawDescData = file_weathercontrol_proto_rawDesc
)

func file_weathercontrol_proto_rawDescGZIP() []byte {
	file_weathercontrol_proto_rawDescOnce.Do(func() {
		file_weathercontrol_proto_rawDescData = protoimpl.X.CompressGZIP(file_weathercontrol_proto_rawDescData)
	})
	return file_weathercontrol_proto_rawDescData
}

var file_weathercontrol_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_weathercontrol_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),  // 0: weathercontrol.v1.GetWeatherRequest
	(*GetWeatherResponse)(nil), // 1: weathercontrol.v1.GetWeatherResponse
	(*SetWeatherRequest)(nil),  // 2: weathercontrol.v1.SetWeatherRequest
	(*SetWeatherResponse)(nil), // 3: weathercontrol.v1.SetWeatherResponse
}
var file_weathercontrol_proto_depIdxs = []int32{
	0, // 0: weathercontrol.v1.WeatherControlService.GetWeather:input_type -> weathercontrol.v1.GetWeatherRequest
	2, // 1: weathercontrol.v1.WeatherControlService.SetWeather:input_type -> weathercontrol.v1.SetWeatherRequest
	1, // 2: weathercontrol.v1.WeatherControlService.GetWeather:output_type -> weathercontrol.v1.GetWeatherResponse
	3, // 3: weathercontrol.v1.WeatherControlService.SetWeather:output_type -> weathercontrol.v1.SetWeatherResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weathercontrol_proto_init() }
func file_weathercontrol_proto_init() {
	if File_weathercontrol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weathercontrol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weathercontrol_proto_goTypes,
		DependencyIndexes: file_weathercontrol_proto_depIdxs,
		MessageInfos:      file_weathercontrol_proto_msgTypes,
	}.Build()
	File_weathercontrol_proto = out.File
	file_weathercontrol_proto_rawDesc = nil
	file_weathercontrol_proto_goTypes = nil
	file_weathercontrol_proto_depIdxs = nil
}
